repos:
-   repo: git@git.yelpcorp.com:mirrors/pre-commit/pre-commit-hooks
    sha: v2.2.3
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: name-tests-test
    -   id: check-added-large-files
    -   id: check-byte-order-marker
    -   id: requirements-txt-fixer
    -   id: fix-encoding-pragma
        args: ['--remove']
-   repo: git@git.yelpcorp.com:mirrors/pre-commit/mirrors-autopep8
    sha: v1.4.2
    hooks:
    -   id: autopep8
-   repo: git@git.yelpcorp.com:mirrors/gitlab/pycqa/flake8
    rev: 3.7.1
    hooks:
    -   id: flake8
-   repo: git@git.yelpcorp.com:mirrors/asottile/reorder_python_imports
    sha: v1.3.2
    hooks:
    -   id: reorder-python-imports
        args: [
            '--remove-import', 'from __future__ import absolute_import',
            '--remove-import', 'from __future__ import unicode_literals',
        ]
-   repo: git@git.yelpcorp.com:mirrors/asottile/pyupgrade
    sha: v1.9.0
    hooks:
    -   id: pyupgrade
        args: [--py3-plus]
-   repo: git@git.yelpcorp.com:mirrors/asottile/add-trailing-comma
    rev: v0.7.1
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
